---
title: "R Notebook"
output: html_notebook
---

```{r}
remove.packages("rlang") 
```
```{r}
install.packages("rlang")
```




```{r}
#install.packages("scales") 
#install.packages("shiny")             # Shiny
#install.packages("shinydashboard")    # Shiny dashboards
#install.packages("DT")  
```



```{r}
library(tidyverse)        
library(shiny)
library(shinydashboard)
library(DT)
library(plotly)
library(gganimate)

load("tidy_vgsales.RData")
```



```{r}
ui <- dashboardPage( skin = "purple",
  
    dashboardHeader(title = "Video Games", titleWidth  = 230),
    
    
    dashboardSidebar( 
      
        sliderInput("sales","Sales filter",
                     min = 0, max = 100,
                     value = c(0,50)), # slider input 1 ends
     
        sliderInput("year", "Year",                        
                    min = 1980, max = 2016,                      
                    value = c(1980, 2016)),  # slider input 2 ends
        
        checkboxGroupInput("region", h4("Region"),               
                           choices = list("North America" = "north_america",
                                          "Europe" = "europe",
                                          "Japan" = "japan",
                                          "Other" = "other",
                                          "Global" = "global"),
                           
                           selected = c("north_america", "europe", "japan", "other", "global"))   # checkbox group ends
        
        ), # dashboard sidebar
    
    dashboardBody(
         
      fluidRow(
        
        # tabbox 1
        tabBox(
              id = "tabset1", height = "1450px", width=12,
              
              # home tabpanel
      
            tabPanel("Home", div(img(src="https://img.redbull.com/images/c_crop,w_2000,h_1000,x_0,y_0,f_auto,q_auto/c_scale,w_1200/redbullcom/2022/2/2/d5qmwzylnjifl8tluhwt/video-games-to-look-out-for-in-february-2022", 
                                      height = 290, width = 890, style="text-align: center;")),
                            
                            
                            fluidRow(
                            box(title = tags$h3("Welcome to my Shiny App on Video Game Sales!", style = "font-family:architectural;                                   font-size: 30px; color: #37115A; font-weight: 150; text-shadow: 2px 2px 2px #aaa;"),height = 1050, width = 12, solidHeader = TRUE,
                                
                                tags$h4("The dataset used to build this shiny app is sourced from kaggle. The duration of the dataset is                                  from 1980 to 2016.", style = "font-family:architectural; font-size: 16px; color: #060606;"),
                                
                                tags$h4("Before we dive deep into the analysis of the dataset, let us understand what makes the video                                     gaming industry (and thus, this dataset) so interesting.", 
                                style = "font-family:architectural; font-size: 16px; color: #060606;"),tags$br(),
                                
                                tags$h3("A short time travel...", style = "font-family:architectural; font-size: 22px; color: #37115A;"),tags$br(),
                                
                                tags$h4("From the time the first arcades hit the streets to the rise of home consoles, the gaming industry has witnessed a remarkable growth in the past few decades.", style = "font-family:architectural; font-size: 16px; color: #060606;"),tags$br(),
                                
                                tags$h4("In 1972, Atari released Pong, a simple arcade table tennis game, which was a huge sensation, officially kickstarting the game industry. Before even entering the eighties, Atari was already making millions selling the first home consoles (Pong 1975) and further strenghting their position in the industry with the release of Space Invaders. ", style = "font-family:architectural; font-size: 16px; color: #060606;"),tags$br(),
                                
                                
                                tags$h4("Did you know? By 1982, arcades were already generating more money than both the pop music industry and the box office!", style = "font-family:architectural; font-size: 16px; color: #060606; font-weight: 150;"),tags$br(),
                                
                                tags$h4("Going a bit further down the line, the gaming industry grew rapidly with the release of Nintendo Entertainment System (NES) home console, Sony's PlayStation in 1984 and legendary games like Super Mario Bros.", style = "font-family:architectural; font-size: 16px; color: #060606;"),tags$br(),
                                
                                tags$h4("However, it was the rise of the internet and mobile in the 2000s that grew the gaming industry from tens of billions to hundreds of billions in revenue.", style = "font-family:architectural; font-size: 16px; color: #060606;"),tags$br(),
                                
                                tags$h4("Here is a short video to bring us back to the present...", style = "font-family:architectural; font-size: 22px; color: #37115A;"), tags$br(),
                                
                                tags$iframe(width="560", height="315", src="https://www.youtube.com/embed/m4OnGNEf5rI", frameborder="0", allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", allowfullscreen=NA)
                              
                                
                                ),
                            ),

                            
                      
                        ), # home tabpanel
            
            # EDA tabpanel
      
            tabPanel("Exploratory Data Analysis", 
                     
                     tags$h4("Inital Data"), 
                     
                      fluidRow(
                      
                        
                        # A static infoBox
                        infoBox("Rows x Columns", tags$h5(strong("16,598 x 11")), color = "yellow", icon = icon("table", style = "color:                          white")),
                        
                        infoBox("Variables", tags$h5(strong("Numerical: 6 Categorical: 5")), color = "purple", icon = icon("info")),
                        
                        infoBox("NAN Values", tags$h5(strong("Year Col: 165")), color = "yellow", icon = icon("bookmark")),
                      ),
                  
                     
                     tags$h4("After pivoting the data"), 
                     
                      # infoBoxes with fill=TRUE
                     
                      fluidRow(
                        infoBox("Rows x Columns", tags$h5(strong("56,625 x 8")), color = "purple", icon = icon("table"), fill = TRUE),
                        
                        infoBox("Variables", tags$h5(strong("Numerical: 2 Categorical: 6")), color = "yellow", icon = icon("info"), fill = TRUE),
                        
                        infoBox("NAN Values", tags$h5(strong("0")), color = "purple", icon = icon("bookmark"), fill = TRUE)
                        
                        
                      ),
                     
                     tags$br(),
                     
                     
                      fluidRow(
                        box(
                          title = "Tidying the data", width = 4, height = 300, solidHeader = TRUE, status = "primary",
                          tags$h4("As we observe, the initial data is not in a tidy format.", style = "font-family:architectural; font-size: 15px; color: #060606;"),tags$br(), 
                          
                          tags$h4("To bring it to tidy format, first all the columns are converted to be in the right format and missing values are removed.", style = "font-family:architectural; font-size: 15px; color: #060606;"),tags$br(), 
                          
                          tags$h4(" Then, the pivot_longer function is used to ensure that all rows are observations and columns are variables. ", style = "font-family:architectural; font-size: 15px; color: #060606;")
                        ),
                        
                        
                        box(
                          title = "Categorical Variables", width = 4, height = 300,status ="primary", solidHeader = TRUE,
                          
                          tags$h4("Unique observations for each variable:", style = "font-family:architectural; font-size: 15px; color: #060606;"),
                         
                          tags$h4("Name (of Video Game): 11328", style = "font-family:architectural; font-size: 15px; color: #060606;"),
                          
                          tags$h4("Platform: 31", style = "font-family:architectural; font-size: 15px; color: #060606;"), 
                          
                          tags$h4("Genre: 12 ", style = "font-family:architectural; font-size: 15px; color: #060606;"),
                          
                          tags$h4("Publisher: 566 ", style = "font-family:architectural; font-size: 15px; color: #060606;"),
                          
                          tags$h4("Region: 5 ", style = "font-family:architectural; font-size: 15px; color: #060606;"),
                          
                          tags$h4("Year: 1980 - 2016 ", style = "font-family:architectural; font-size: 15px; color: #060606;")
                           
                        ),
                        
                        
                        box(
                          title = "Numerical Variables", width = 4, height = 300, solidHeader = TRUE, status = "primary",
                          
                          tags$h4("There are 2 numerical variables - Rank and Sales.", style = "font-family:architectural; font-size: 15px; color: #060606;"),
                         
                          tags$h4("The original dataset had 5 regions for sales, namely, North America, Europe, Japan, Other and Global. These 5 columns were merged together using pivot_longer to keep one column, 'Sales'.", style = "font-family:architectural; font-size: 15px; color: #060606;")
                           
                        )
                      )
                  
                      ), # EDA tabpanel
            
            # viz tabpanel
  
            tabPanel("Visualization" , 
                      
                              fluidRow(
                                tabBox(
                                  side = "right", height = "320px", width = 12,
                                  
                                  selected = "Sales",
                                  
                                  tabPanel( title = "Games", height = 300, width = 12, solidHeader = FALSE, 
                                 plotOutput("gameplot", height = 600),
                                 
                                 hr(),
                                
                                selectInput("genre", "Pick a genre",
                                choices = tidy_vgsales$genre %>% unique() %>% sort(),
                                selected = c("Action", "Sports", "Role-Playing", "Shooter",         "Simulation","Racing","Puzzle","Platform","Misc","Adventure","Fighting","Strategy"), multiple = TRUE)
                                
                                ),
                                  
                                  tabPanel(title = "Publisher", height = 300, width = 12, solidHeader = FALSE, 
                                 
                                           fluidRow( 
                                box(
                                  title = "", solidHeader = TRUE,
                                  collapsible = TRUE,
                                  plotOutput("publisherplot", height = 250)
                                ),
                                
                                box(
                                  title = "", solidHeader = TRUE,
                                  collapsible = TRUE,
                                  plotOutput("publisherplot2", height = 250)
                                )
                                ),
                                
                                hr(),
                                
                                selectInput("genre", "Pick a genre",
                                choices = tidy_vgsales$genre %>% unique() %>% sort(),
                                selected = c("Action", "Sports", "Role-Playing", "Shooter",         "Simulation","Racing","Puzzle","Platform","Misc","Adventure","Fighting","Strategy"), multiple = TRUE)
                                
                                
                                           
                                           ), #publisher panel ends
                                  
                                
                                  tabPanel(title = "Platform", height = 300, width = 12, solidHeader = FALSE, 
                                 
                                
                                fluidRow( 
                                box(
                                  title = "", solidHeader = TRUE,
                                  collapsible = TRUE,
                                  plotOutput("platformplot", height = 250)
                                ),
                                
                                box(
                                  title = "", solidHeader = TRUE,
                                  collapsible = TRUE,
                                  plotOutput("platformplot2", height = 250)
                                )
                                ),
                                
                                hr(),
                                
                                selectInput("genre", "Pick a genre",
                                choices = tidy_vgsales$genre %>% unique() %>% sort(),
                                selected = c("Action", "Sports", "Role-Playing", "Shooter",         "Simulation","Racing","Puzzle","Platform","Misc","Adventure","Fighting","Strategy"), multiple = TRUE)
                                
                                
                                ), # platform panel ends
                                  
                                  
                                  tabPanel(title = "Genre", height = 300, width = 12, solidHeader = FALSE, 
                                 plotOutput("genreplot", height = 300),
                                 
                                 fluidRow(
                                 box(
                                  title = "", solidHeader = TRUE,
                                  collapsible = TRUE,
                                  plotOutput("genreplot2", height = 250)
                                ),
                                
                                box(
                                  title = "", solidHeader = TRUE,
                                  collapsible = TRUE,
                                  plotOutput("genreplot3", height = 250)
                                )
                                 )
                                 
                                 #fluidPage(
    
                                  # Copy the line below to make a select box 
                                  #selectInput("select", label = tags$h3("Check for a particular platform",style = "font-family:architectural; font-size: 15px; color: #060606;" ), 
                                    #choices = list(
                                      #"PS" = "PS", 
                                      #"PS2" = "PS2", 
                                      #"PS3" = "PS3",
                                      #"PS4" = "PS4", 
                                      #"XB" = "XB", 
                                      #"X360" = "X360",
                                      #"Wii" = "Wii", 
                                      #"DS" = "DS", 
                                      #"3DS" = "3DS",
                                      #"PC" = "PC", 
                                      #"GB" = "GB", 
                                      #"GBA" = "GBA",
                                      #"All" = tidy_vgsales$platform %>% unique() %>% sort()), 
                                    #selected = tidy_vgsales$platform %>% unique() %>% sort(), multiple = TRUE),
                                  
                                  #hr(),
                                  #fluidRow(column(3, verbatimTextOutput("value")))
                                  
                                #)
                                ), # genre panel ends
                                  
                                  tabPanel( title = "Sales", height = 400, width = 12, solidHeader = FALSE, 
                                 plotOutput("salesplot", height = 300),
                                 
                                 fluidRow(
                            box(title = "",height = 400, width = 12, solidHeader = TRUE,
                                 
                                 plotOutput("salesplot2", height = 300))))
                      
      
                            
                            ) # tabbox
                            
                            ) # viz fluid row
                     
                     ), #viz tabpanel

  
            tabPanel("Insights", 
                     
                    
                     
                     hr(),
                     
                     fluidRow(
                        box(
                          title = "Region with Highest Sales:", width = 4, height = 250, background = "yellow",
                          
                         
                          tags$h4(strong("North America",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;"))
                          
                        ),
                        box(
                          title = "Best Performing Games:", width = 4, height = 250, background = "teal",
                          
                          
                          tags$h4(strong("1. Wii",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("2. Super Mario Bros",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("3. Mario Kart Wii ",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("4. Wii Sports Resort",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("5. Pokemon Red/Pokemon Blue",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;"))
                        ),
                        
                        box(
                          title = "Best Performering Genre:",width = 4, height = 250, background = "olive",
                          
                          
                          tags$h4(strong("1. Action",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("2. Sports",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("3. Role-Playing",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("4. Shooter",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("5. Simulation",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;"))
                        )
                      ),
                     
                     fluidRow(
                        box(
                         title = "Best Performing Platforms:", width = 4, height = 250, background = "purple",
                          
                         
                          tags$h4(strong("1. PS2",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("2. Wii",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("3. DS",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("4. PS",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("5. X360",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;"))
                          
                        ),
                        
                        box(
                          title = "Best Performing Publishers:", width = 4, height = 250, background = "maroon",
                          
                          
                          tags$h4(strong("1. Nintendo",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("2. Electronic Arts",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("3. Sony Computer Entertainment",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("4. Activision",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;")),
                          tags$h4(strong("5. Ubisoft",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;"))
                        ),
                        
                        box(
                          title = "Years with Highest Sales",width = 4, height = 250,background = "black",
                          
                          tags$h4(strong("2008 & 2009",style = "font-family:architectural; font-size: 15px; color: #FFFFFF;"))
                        )
                      )
                     
                     ),
  
            tabPanel("Data", DT::dataTableOutput("table"))
                     
            
  
      
    

) # tabbox1

) # fluidrow encompassing entire dashboard body
) # dashboard body
) # dashboard page





server <- function(input, output){
  
  # CREATING REACTIVE DATA 
    
    data <- reactive({            
        tidyvgsales <- tidy_vgsales %>%      
            filter(sales >= input$sales[1], 
                   sales <= input$sales[2],
                   
                   year >= input$year[1],
                   year <= input$year[2],
                   
                  region %in% input$region,
                  genre %in% input$genre
                  ) 
        
        return(tidyvgsales)
    })
    
    output$table <- DT::renderDataTable(data(), rownames = FALSE)
    
    # HOME TAB
    
    # EDA
    
    
    output$salesplot <- renderPlot({
        data() %>% 
            group_by(year) %>%
            summarize(total_sales = sum(sales)) %>%  
            ggplot(aes(x = year, y = total_sales, group = 1, color=year)) + 
            geom_line() + geom_point() + theme_light()+
     
            theme(axis.text.x = element_text(angle = 90)) +
            labs(x = "Years", y = "Total Sales", caption = "Graph 1")
    }, height = 300)
    
    
    output$salesplot2 <- renderPlot({
        data() %>% 
            group_by(region, year) %>%
            summarize(avg_sales = mean(sales)) %>%  
            ggplot(aes(x = year, y = avg_sales, color=region)) + 
            geom_line() + geom_point()  + theme_light()+
     
            theme(axis.text.x = element_text(angle = 90)) +
            labs(x = "Years", y = "Average Sales", caption = "Graph 2")
    }, height = 300)
    
    
    
    output$genreplot <- renderPlot({
        data() %>% 
            ggplot(aes(x = fct_rev(reorder(genre, -sales)), y = sales)) + geom_col(fill="#8876C7", alpha=0.7) + theme_minimal()+
            labs(title = "Most Popular Genre over the years",
            x = "Genre of the Video game", y = "Total Sales (in millions)", caption = "Graph 3") +
            theme(text = element_text(size = 12, color = "#2D4F0C"),          
            axis.text.x = element_text(angle = 45, color = "black"))
    }, height = 300)
    
    output$genreplot2 <- renderPlot({
        data() %>% 
            ggplot(aes(x = reorder(genre,sales), y = sales, fill = region)) + geom_col(alpha=0.8) + 
            scale_color_brewer(palette = "Spectral")+ theme_minimal()+
            labs(title = "Most Popular Genre over the regions",
                 x = "Genre of the Video game", y = "Total Sales", caption = "Graph 4")+
            theme(text = element_text(size = 12, color = "#2D4F0C"),          
                  axis.text.x = element_text(angle = 45, color = "black"))
    }, height = 300)
    
    
    output$genreplot3 <- renderPlot({
        data() %>% 
            group_by(year, genre) %>%
            summarize(total_sales = sum(sales)) %>% 
            ggplot(aes(x = year, y = total_sales, fill = genre)) + geom_col(alpha=0.8) + 
            scale_color_brewer(palette = "Spectral")+ theme_minimal()+
            labs(title = "Distribution of Genres most sold over the years",
                 x = "Year of release", y = "Total Sales", caption = "Graph 5") +
            theme(text = element_text(size = 12, color = "#2D4F0C"),          
                  axis.text.x = element_text(angle = 45, color = "black"))
    }, height = 300)
    
    
    #output$value <- renderPrint({ input$select })

    
    output$platformplot <- renderPlot({
        platform_sales <- data() %>% 
        group_by(platform) %>% 
        summarise(total_sales = sum(sales), .groups = 'drop') %>% 
        arrange(desc(total_sales)) %>%
        mutate(percent_sales = total_sales/sum(total_sales)*100)

        ggplot(data= head(platform_sales, 10), aes(x= "", y=percent_sales, fill = platform)) +
        geom_bar(stat="identity", color = 'yellow') +
        coord_polar("y", start=0) + # to create the circle
        theme(axis.text.x = element_text()) + theme(axis.title = element_text(size = 10)) +
        labs(title = "Top performing platforms", y = "", x = "", colour = "Blue", caption = "Graph 6") +
        geom_text(aes(label = paste0(round(percent_sales),"%")), position = position_stack(vjust = 0.5),color = "black",size=4)
    }, height = 300)
    
    
    output$platformplot2 <- renderPlot({
        
      top_platform <- data() %>% 
                        group_by(platform, region) %>%
                        summarize(total_sales = sum(sales)) %>%
                        arrange(desc(total_sales)) %>%
                        filter(total_sales > 100) 
      
      
      top_platform %>% 
            ggplot(aes(x = reorder(platform,total_sales), y = total_sales, fill=region)) + geom_col(alpha=0.8) + 
            scale_color_brewer(palette = "Spectral")+ theme_minimal()+
            labs(title = "Regional Distribution of Platforms with more than 100 million sales",
                 x = "Platforms", y = "Total Sales (in millions)",caption="Graph 7")+
            theme(text = element_text(size = 12, color = "#2D4F0C"),          
                  axis.text.x = element_text(angle = 45, color = "black"))

    }, height = 300)
    
    
    output$publisherplot <- renderPlot({
        publisher_sales <- data() %>% 
        group_by(publisher) %>% 
        summarise(total_sales = sum(sales), .groups = 'drop') %>% 
        arrange(desc(total_sales)) %>%
        mutate(percent_sales = total_sales/sum(total_sales)*100)

        ggplot(data= head(publisher_sales, 10), aes(x= "", y=percent_sales, fill = publisher)) +
        geom_bar(stat="identity", color = 'yellow') +
        coord_polar("y", start=0) + # to create the circle
        theme(axis.text.x = element_text()) + theme(axis.title = element_text(size = 10)) +
        labs(title = "Top performing Publishers", y = "", x = "", colour = "Blue", caption = "Graph 8") +
        geom_text(aes(label = paste0(round(percent_sales),"%")), position = position_stack(vjust = 0.5),color = "black",size=4)
    }, height = 300)
    
    
    output$publisherplot2 <- renderPlot({
        
      top_publisher <- data() %>% 
                        group_by(publisher, region) %>%
                        summarize(total_sales = sum(sales)) %>%
                        arrange(desc(total_sales)) %>%
                        filter(total_sales > 100) 
      
      
      top_publisher %>% 
            ggplot(aes(x = reorder(publisher,total_sales), y = total_sales, fill=region)) + geom_col(alpha=0.8) + 
            scale_color_brewer(palette = "Spectral")+ theme_minimal()+
            labs(title = "Regional Distribution of Publishers with more than 100 million sales",
                 x = "Publisher", y = "Total Sales",caption="Graph 9")+
            theme(text = element_text(size = 12, color = "#2D4F0C"),          
                  axis.text.x = element_text(angle = 90, color = "black"))

    }, height = 300)
    
    
    output$gameplot <- renderPlot({
        
      top_name <- data() %>% 
                        group_by(name) %>%
                        summarize(total_sales = sum(sales)) %>%
                        arrange(desc(total_sales)) %>%
                        top_n(50, total_sales)
              
      
      
      top_name %>% 
            ggplot(aes(y = reorder(name,total_sales), x = total_sales)) + geom_col(fill = "#4275F0", alpha = 0.5) + 
            theme_minimal() +
            labs(title = "Top selling games",
                 x = "Sales", y = "Games",caption="Graph 10")+
            theme(text = element_text(size = 14, color = "#2D4F0C"),          
                  axis.text.y = element_text(color = "black"))

    }, height = 600)
    
    
    
    
}

# Run the app ----
shinyApp(ui = ui, server = server)  # Aggregates the app.

```

